spring:
  datasource:
    url:  jdbc:h2:file:~/data/demo
    driverClassName:  org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform:  org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        hbm2ddl:
          auto: update
    hibernate:
      naming:
        physical-strategy:  org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
